-- MySQL Script generated by MySQL Workbench
-- Thu Feb 24 13:38:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema munchbase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `munchbase` ;

-- -----------------------------------------------------
-- Schema munchbase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `munchbase` DEFAULT CHARACTER SET utf8 ;
USE `munchbase` ;
